### ISSUE TITLE
Fails with Amazon RSS

### ISSUE THREAD

**Issue by 2braincells2go** [bbClassic/YRSS#2]
Testing and really like simplicity of YRSS.

Got ready to add feed for a blog using Amazon. Doing so throws an error.

Using Amazon standard URL;

http://www.amazon.com/gp/rss/bestsellers/photo/ref=zg_bs_photo_rsslink?tag=YOURID-20

(even tried http://www.amazon.com/gp/rss/bestsellers/photo?tag=YOURID-20)

Error shown in console:

`  Uncaught TypeError: Cannot read property 'item' of null  yrss.js:92
    at process (yrss.js:92)
    at Object.success (yrss.js:53)
    at i (jquery-3.1.1.min.js:2)
    at Object.fireWith [as resolveWith] (jquery-3.1.1.min.js:2)
    at A (jquery-3.1.1.min.js:4)
    at XMLHttpRequest.<anonymous> (jquery-3.1.1.min.js:4)`

Ran out of ideas to solve and hoping maybe you can give some advice.

Thanks!

**Comment by markhillard** [comment]
Hi @2braincells2go, go to https://developer.yahoo.com/yql/console/#h=select+*+from+feed+where+url%3D%22http%3A%2F%2Fwww.amazon.com%2Fgp%2Frss%2Fbestsellers%2Fphoto%2Fref%3Dzg_bs_photo_rsslink%3Ftag%3DYOURID-20%22 and click on the **Test** button. I was able to return results from that query using the YQL console.

I thought it was strange that it was not working for you so I tested the script locally, using `<script src="https://rawgit.com/bbClassic/YRSS/master/yrss.min.js"></script>` in my demo HTML file. It didn't work for me either, but then I updated the query URL to use **https** (https://www.amazon.com/gp/rss/bestsellers/photo/ref=zg_bs_photo_rsslink?tag=YOURID-20) and then I set the `ssl` option to `true` in the `rssfeed()` method. After I did that it worked and the feed was being loaded.

```js
var feed1 = 'https://www.amazon.com/gp/rss/bestsellers/photo/ref=zg_bs_photo_rsslink?tag=YOURID-20';
$('#feed').rssfeed(feed1, {
    ssl: true,
    limit: 20,
    showerror: true,
    errormsg: '',
    tags: true,
    date: true,
    dateformat: 'spellmonth',
    titletag: 'h4',
    content: true,
    image: true,
    snippet: true,
    snippetlimit: 120,
    linktarget: '_blank'
}, function () {
    // optional callback function
});
```

This type of scenario is actually why I included an option to enable or disable **https**. Try making sure everything is loaded via **https** and let me know if that works for you.

**Comment by 2braincells2go** [comment]
Thanks Mark. I did try enable SSL & using https (b4 opening issue) and not working for me. Must be something else going on with my end. If works for you then case closed.

Thanks again for replying.

Woody

**Comment by markhillard** [comment]
No problem Woody. If you want, download [demo.html](https://github.com/bbClassic/YRSS/blob/master/demo.html) and adjust the script accordingly at the bottom then open it up in your browser. That's the file I used for my test... maybe you'll have some better luck.

**Comment by 2braincells2go** [comment]
Yes sir, works in local demo.html but still having issues on my end. Once I have it on (test) server will not work. Must have something to do with server SSL. I get "Uncaught TypeError: Cannot read property 'item' of null yrss.js:92". Will pick up on troubleshooting next week and if find solution will report back.

Cheers!
