### ISSUE TITLE
Feeds are no longer shown

### ISSUE THREAD

**Issue by oleteacher** [bbClassic/YRSS#7]
**Describe the bug**
I have not noticed this issue until updating to latest PHP 7.1.23. Not 100% sure PHP 7  is the issue, but that only thing that has changed on my end. Running same versions of jQuery.

I updated to YRSS 1.1.7 in hopes of fixing, no change...

The feeds no longer appear and the following is from dev console:

```
Uncaught TypeError: Cannot read property 'item' of null
    at s (yrss.min.js:4)
    at Object.success (yrss.min.js:4)
    at u (jquery.min.js:2)
    at Object.fireWith [as resolveWith] (jquery.min.js:2)
    at k (jquery.min.js:2)
    at XMLHttpRequest.<anonymous> (jquery.min.js:2)
```
Any ideas how to fix this?

**Screenshots**
![image](https://user-images.githubusercontent.com/26278259/49131052-33a3e880-f29c-11e8-960d-3629df821be4.png)

**Desktop (please complete the following information):**
 - OS: Win 10 Pro
 - Chrome
 - Version 70.0.3538.110 (Official Build) (64-bit)

**Comment by markhillard** [comment]
@oleteacher do you have a public URL that I can visit to troubleshoot? Or are you developing locally? This appears to be an issue with how the data is formatted within the RSS feed itself. Can you create a jsFiddle or CodePen test case with that same feed URL and see if it works elsewhere?

**Comment by markhillard** [comment]
Oops, accidentally closed the issue.

**Comment by oleteacher** [comment]
Thank you for reply @markhillard 

I think got it figured out few minutes ago. Amazing what good nights sleep will do for one:)

I stated nothing had changed except PHP7 version. That was not totally true...

I was unaware that my partner (husband) had changed the RSS feed URL from http:// to https://. Seems that the SSL setting was still set to "false". Changed the URL back to http:// and all works.

This error appears when feed URL is set to https:// and `ssl: false,` is not changed to true. Did not test by setting to `ssl: true,` but seems logical.

Thanks for the great RSS script!

**Comment by markhillard** [comment]
@oleteacher glad you got it working again and thanks for the kinds words. I've ran into that issue before because of the `ssl` option too, but the error is pretty generic so it's not the most obvious fix.

If you set the feed URL to `https://` and `ssl: true` it should work as long as the site you're running the script on has an SSL cert.
