### ISSUE TITLE
Plugin stopped working

### ISSUE THREAD

**Issue by dinesh4735** [bbClassic/YRSS#8]
**Describe the bug**
Plugin suddenly stopped working and evn the demo page is blank

**Expected behavior**
Feed should load

![yrss-error](https://user-images.githubusercontent.com/7506002/50667642-218a2980-0f6f-11e9-9097-89cc0d59712c.PNG)

**Comment by markhillard** [comment]
Welp, looks like my plugin is completely useless now. I went to the [YQL homepage](https://developer.yahoo.com/yql/) and it appears they've retired the service completely...

![screenshot_2019-01-03 yql - yahoo developer network](https://user-images.githubusercontent.com/8247756/50668179-79cf2480-0f8b-11e9-8665-7d42c8a5b040.png)

Sorry, but there's nothing I can do to fix it, unless you know of a similar service on the web?
